# Generated by Django 5.2.6 on 2025-09-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
