# Generated by Django 5.2.6 on 2025-09-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_predictionhistory_age_predictionhistory_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
