# Generated by Django 5.2.6 on 2025-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_predictionhistory_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionhistory',
            name='size',
            field=models.IntegerField(),
        ),
    ]
