# Generated by Django 5.2.6 on 2025-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_alter_predictionhistory_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
